# Generated by Django 3.1.5 on 2021-01-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
