# Generated by Django 3.1.5 on 2021-01-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_due_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='due',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
