# Generated by Django 3.1.5 on 2021-01-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210121_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='due',
            name='query',
            field=models.DateField(blank=True, null=True),
        ),
    ]
