# Generated by Django 3.1.5 on 2021-01-21 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210121_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='query',
            field=models.DateField(default=datetime.date(2021, 1, 21)),
        ),
    ]
