# Generated by Django 3.1.5 on 2021-01-21 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210121_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='query',
            field=models.DateField(default=datetime.datetime(2021, 1, 21, 15, 28, 12, 869809)),
        ),
    ]
